[package]
name = "wensai"
version = "0.1.0"
description = "WenSai desktop shell"
authors = ["WenSai"]
edition = "2021"

[lib]
name = "wensai"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }

